basePath: /
definitions:
  router.InstructionD:
    properties:
      agentUUID:
        default: c3cb84233416497694569d759a8a13e7
        description: 'example: Test'
        type: string
      instructionUUID:
        default: 32a2833486414af9bc4596caef585538
        type: string
      procedureID:
        default: P_Collection_Kimsuky_001
        description: 'example: Test'
        type: string
    type: object
host: localhost:80
info:
  contact:
    email: support@managingserver.io
    name: ManagingServer API Support
    url: http://managingserver.io/support
  description: This is a sample server for the ManagingServer project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://managingserver.io/terms/
  title: ManagingServer API
  version: "1.0"
paths:
  /api/postInst:
    post:
      consumes:
      - application/json
      description: get struct array by ID
      operationId: get-struct-array2-by-string
      parameters:
      - description: request job
        in: body
        name: loginUserRequest
        required: true
        schema:
          $ref: '#/definitions/router.InstructionD'
      produces:
      - application/json
      responses: {}
swagger: "2.0"
