basePath: /
definitions:
  router.InstructionD:
    properties:
      agentUUID:
        default: 937640a858ad48e9bc2787e8c4456ced
        description: 'example: Test'
        type: string
      instructionUUID:
        default: 32a2833486414af9bc4596caef585538
        type: string
      procedureID:
        default: P_Collection_Kimsuky_001
        description: 'example: Test'
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/postInst:
    post:
      consumes:
      - application/json
      description: get struct array by ID
      operationId: get-struct-array2-by-string
      parameters:
      - description: request job
        in: body
        name: loginUserRequest
        required: true
        schema:
          $ref: '#/definitions/router.InstructionD'
      produces:
      - application/json
      responses: {}
swagger: "2.0"
